/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.information_schema.tables;


import bookmanagementsystem.jooq.information_schema.Domains;
import bookmanagementsystem.jooq.information_schema.InformationSchema;
import bookmanagementsystem.jooq.information_schema.tables.records.UserMappingsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UserMappings extends TableImpl<UserMappingsRecord> {

    /**
     * The reference instance of <code>information_schema.user_mappings</code>
     */
    public static final UserMappings USER_MAPPINGS = new UserMappings();
    private static final long serialVersionUID = 1L;
    /**
     * The column
     * <code>information_schema.user_mappings.authorization_identifier</code>.
     */
    public final TableField<UserMappingsRecord, String> AUTHORIZATION_IDENTIFIER = createField(DSL.name("authorization_identifier"), Domains.SQL_IDENTIFIER.getDataType(), this, "");
    /**
     * The column
     * <code>information_schema.user_mappings.foreign_server_catalog</code>.
     */
    public final TableField<UserMappingsRecord, String> FOREIGN_SERVER_CATALOG = createField(DSL.name("foreign_server_catalog"), Domains.SQL_IDENTIFIER.getDataType(), this, "");
    /**
     * The column
     * <code>information_schema.user_mappings.foreign_server_name</code>.
     */
    public final TableField<UserMappingsRecord, String> FOREIGN_SERVER_NAME = createField(DSL.name("foreign_server_name"), Domains.SQL_IDENTIFIER.getDataType(), this, "");

    private UserMappings(Name alias, Table<UserMappingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserMappings(Name alias, Table<UserMappingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
                create view "user_mappings" as  SELECT authorization_identifier,
                 foreign_server_catalog,
                 foreign_server_name
                FROM information_schema._pg_user_mappings;
                """), where);
    }

    /**
     * Create an aliased <code>information_schema.user_mappings</code> table
     * reference
     */
    public UserMappings(String alias) {
        this(DSL.name(alias), USER_MAPPINGS);
    }

    /**
     * Create an aliased <code>information_schema.user_mappings</code> table
     * reference
     */
    public UserMappings(Name alias) {
        this(alias, USER_MAPPINGS);
    }

    /**
     * Create a <code>information_schema.user_mappings</code> table reference
     */
    public UserMappings() {
        this(DSL.name("user_mappings"), null);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMappingsRecord> getRecordType() {
        return UserMappingsRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public UserMappings as(String alias) {
        return new UserMappings(DSL.name(alias), this);
    }

    @Override
    public UserMappings as(Name alias) {
        return new UserMappings(alias, this);
    }

    @Override
    public UserMappings as(Table<?> alias) {
        return new UserMappings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMappings rename(String name) {
        return new UserMappings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMappings rename(Name name) {
        return new UserMappings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMappings rename(Table<?> name) {
        return new UserMappings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings where(Condition condition) {
        return new UserMappings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMappings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMappings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMappings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMappings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMappings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
