/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.information_schema.tables.records;


import bookmanagementsystem.jooq.information_schema.tables.RoleUsageGrants;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class RoleUsageGrantsRecord extends TableRecordImpl<RoleUsageGrantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached RoleUsageGrantsRecord
     */
    public RoleUsageGrantsRecord() {
        super(RoleUsageGrants.ROLE_USAGE_GRANTS);
    }

    /**
     * Create a detached, initialised RoleUsageGrantsRecord
     */
    public RoleUsageGrantsRecord(String grantor, String grantee, String objectCatalog, String objectSchema, String objectName, String objectType, String privilegeType, String isGrantable) {
        super(RoleUsageGrants.ROLE_USAGE_GRANTS);

        setGrantor(grantor);
        setGrantee(grantee);
        setObjectCatalog(objectCatalog);
        setObjectSchema(objectSchema);
        setObjectName(objectName);
        setObjectType(objectType);
        setPrivilegeType(privilegeType);
        setIsGrantable(isGrantable);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>information_schema.role_usage_grants.grantor</code>.
     */
    public String getGrantor() {
        return (String) get(0);
    }

    /**
     * Setter for <code>information_schema.role_usage_grants.grantor</code>.
     */
    public void setGrantor(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema.role_usage_grants.grantee</code>.
     */
    public String getGrantee() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.role_usage_grants.grantee</code>.
     */
    public void setGrantee(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>information_schema.role_usage_grants.object_catalog</code>.
     */
    public String getObjectCatalog() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>information_schema.role_usage_grants.object_catalog</code>.
     */
    public void setObjectCatalog(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>information_schema.role_usage_grants.object_schema</code>.
     */
    public String getObjectSchema() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>information_schema.role_usage_grants.object_schema</code>.
     */
    public void setObjectSchema(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>information_schema.role_usage_grants.object_name</code>.
     */
    public String getObjectName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>information_schema.role_usage_grants.object_name</code>.
     */
    public void setObjectName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>information_schema.role_usage_grants.object_type</code>.
     */
    public String getObjectType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>information_schema.role_usage_grants.object_type</code>.
     */
    public void setObjectType(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>information_schema.role_usage_grants.privilege_type</code>.
     */
    public String getPrivilegeType() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>information_schema.role_usage_grants.privilege_type</code>.
     */
    public void setPrivilegeType(String value) {
        set(6, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for
     * <code>information_schema.role_usage_grants.is_grantable</code>.
     */
    public String getIsGrantable() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>information_schema.role_usage_grants.is_grantable</code>.
     */
    public void setIsGrantable(String value) {
        set(7, value);
    }
}
