/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.information_schema.tables.records;


import bookmanagementsystem.jooq.information_schema.tables.Tables;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablesRecord extends TableRecordImpl<TablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>information_schema.tables.table_catalog</code>.
     */
    public void setTableCatalog(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema.tables.table_catalog</code>.
     */
    public String getTableCatalog() {
        return (String) get(0);
    }

    /**
     * Setter for <code>information_schema.tables.table_schema</code>.
     */
    public void setTableSchema(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>information_schema.tables.table_schema</code>.
     */
    public String getTableSchema() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.tables.table_name</code>.
     */
    public void setTableName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>information_schema.tables.table_name</code>.
     */
    public String getTableName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>information_schema.tables.table_type</code>.
     */
    public void setTableType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>information_schema.tables.table_type</code>.
     */
    public String getTableType() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>information_schema.tables.self_referencing_column_name</code>.
     */
    public void setSelfReferencingColumnName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>information_schema.tables.self_referencing_column_name</code>.
     */
    public String getSelfReferencingColumnName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>information_schema.tables.reference_generation</code>.
     */
    public void setReferenceGeneration(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>information_schema.tables.reference_generation</code>.
     */
    public String getReferenceGeneration() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>information_schema.tables.user_defined_type_catalog</code>.
     */
    public void setUserDefinedTypeCatalog(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>information_schema.tables.user_defined_type_catalog</code>.
     */
    public String getUserDefinedTypeCatalog() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>information_schema.tables.user_defined_type_schema</code>.
     */
    public void setUserDefinedTypeSchema(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>information_schema.tables.user_defined_type_schema</code>.
     */
    public String getUserDefinedTypeSchema() {
        return (String) get(7);
    }

    /**
     * Setter for <code>information_schema.tables.user_defined_type_name</code>.
     */
    public void setUserDefinedTypeName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>information_schema.tables.user_defined_type_name</code>.
     */
    public String getUserDefinedTypeName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>information_schema.tables.is_insertable_into</code>.
     */
    public void setIsInsertableInto(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>information_schema.tables.is_insertable_into</code>.
     */
    public String getIsInsertableInto() {
        return (String) get(9);
    }

    /**
     * Setter for <code>information_schema.tables.is_typed</code>.
     */
    public void setIsTyped(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>information_schema.tables.is_typed</code>.
     */
    public String getIsTyped() {
        return (String) get(10);
    }

    /**
     * Setter for <code>information_schema.tables.commit_action</code>.
     */
    public void setCommitAction(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>information_schema.tables.commit_action</code>.
     */
    public String getCommitAction() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablesRecord
     */
    public TablesRecord() {
        super(Tables.TABLES);
    }

    /**
     * Create a detached, initialised TablesRecord
     */
    public TablesRecord(String tableCatalog, String tableSchema, String tableName, String tableType, String selfReferencingColumnName, String referenceGeneration, String userDefinedTypeCatalog, String userDefinedTypeSchema, String userDefinedTypeName, String isInsertableInto, String isTyped, String commitAction) {
        super(Tables.TABLES);

        setTableCatalog(tableCatalog);
        setTableSchema(tableSchema);
        setTableName(tableName);
        setTableType(tableType);
        setSelfReferencingColumnName(selfReferencingColumnName);
        setReferenceGeneration(referenceGeneration);
        setUserDefinedTypeCatalog(userDefinedTypeCatalog);
        setUserDefinedTypeSchema(userDefinedTypeSchema);
        setUserDefinedTypeName(userDefinedTypeName);
        setIsInsertableInto(isInsertableInto);
        setIsTyped(isTyped);
        setCommitAction(commitAction);
        resetChangedOnNotNull();
    }
}
