/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.information_schema.tables.records;


import bookmanagementsystem.jooq.information_schema.tables.UdtPrivileges;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UdtPrivilegesRecord extends TableRecordImpl<UdtPrivilegesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached UdtPrivilegesRecord
     */
    public UdtPrivilegesRecord() {
        super(UdtPrivileges.UDT_PRIVILEGES);
    }

    /**
     * Create a detached, initialised UdtPrivilegesRecord
     */
    public UdtPrivilegesRecord(String grantor, String grantee, String udtCatalog, String udtSchema, String udtName, String privilegeType, String isGrantable) {
        super(UdtPrivileges.UDT_PRIVILEGES);

        setGrantor(grantor);
        setGrantee(grantee);
        setUdtCatalog(udtCatalog);
        setUdtSchema(udtSchema);
        setUdtName(udtName);
        setPrivilegeType(privilegeType);
        setIsGrantable(isGrantable);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>information_schema.udt_privileges.grantor</code>.
     */
    public String getGrantor() {
        return (String) get(0);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.grantor</code>.
     */
    public void setGrantor(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema.udt_privileges.grantee</code>.
     */
    public String getGrantee() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.grantee</code>.
     */
    public void setGrantee(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>information_schema.udt_privileges.udt_catalog</code>.
     */
    public String getUdtCatalog() {
        return (String) get(2);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.udt_catalog</code>.
     */
    public void setUdtCatalog(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>information_schema.udt_privileges.udt_schema</code>.
     */
    public String getUdtSchema() {
        return (String) get(3);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.udt_schema</code>.
     */
    public void setUdtSchema(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>information_schema.udt_privileges.udt_name</code>.
     */
    public String getUdtName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.udt_name</code>.
     */
    public void setUdtName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>information_schema.udt_privileges.privilege_type</code>.
     */
    public String getPrivilegeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.privilege_type</code>.
     */
    public void setPrivilegeType(String value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>information_schema.udt_privileges.is_grantable</code>.
     */
    public String getIsGrantable() {
        return (String) get(6);
    }

    /**
     * Setter for <code>information_schema.udt_privileges.is_grantable</code>.
     */
    public void setIsGrantable(String value) {
        set(6, value);
    }
}
