/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.routines;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ArrayLarger extends AbstractRoutine<Object[]> {

    /**
     * The parameter <code>pg_catalog.array_larger.RETURN_VALUE</code>.
     */
    public static final Parameter<Object[]> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.OTHER.array(), false, false);
    /**
     * The parameter <code>pg_catalog.array_larger._1</code>.
     */
    public static final Parameter<Object[]> _1 = Internal.createParameter("_1", SQLDataType.OTHER.array(), false, true);
    /**
     * The parameter <code>pg_catalog.array_larger._2</code>.
     */
    public static final Parameter<Object[]> _2 = Internal.createParameter("_2", SQLDataType.OTHER.array(), false, true);
    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public ArrayLarger() {
        super("array_larger", PgCatalog.PG_CATALOG, SQLDataType.OTHER.array());

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
        addInParameter(_2);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(Object[] value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void set__1(Field<Object[]> field) {
        setField(_1, field);
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    public void set__2(Object[] value) {
        setValue(_2, value);
    }

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void set__2(Field<Object[]> field) {
        setField(_2, field);
    }
}
