/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.routines;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgCreateLogicalReplicationSlot extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME1 = Internal.createParameter("slot_name", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.plugin</code>.
     */
    public static final Parameter<String> PLUGIN = Internal.createParameter("plugin", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.temporary</code>.
     */
    public static final Parameter<Boolean> TEMPORARY = Internal.createParameter("temporary", SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), true, false);

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.twophase</code>.
     */
    public static final Parameter<Boolean> TWOPHASE = Internal.createParameter("twophase", SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), true, false);

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.failover</code>.
     */
    public static final Parameter<Boolean> FAILOVER = Internal.createParameter("failover", SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), true, false);

    /**
     * The parameter
     * <code>pg_catalog.pg_create_logical_replication_slot.slot_name</code>.
     */
    public static final Parameter<String> SLOT_NAME6 = Internal.createParameter("slot_name", SQLDataType.VARCHAR, false, false);

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public static final Parameter<Object> LSN = Internal.createParameter("lsn", DefaultDataType.getDefaultDataType("\"pg_catalog\".\"pg_lsn\""), false, false);

    /**
     * Create a new routine call instance
     */
    public PgCreateLogicalReplicationSlot() {
        super("pg_create_logical_replication_slot", PgCatalog.PG_CATALOG);

        addInOutParameter(SLOT_NAME1);
        addInParameter(PLUGIN);
        addInParameter(TEMPORARY);
        addInParameter(TWOPHASE);
        addInParameter(FAILOVER);
        addInOutParameter(SLOT_NAME6);
        addOutParameter(LSN);
    }

    /**
     * Set the <code>slot_name</code> parameter IN value to the routine
     */
    public void setSlotName1(String value) {
        setValue(SLOT_NAME1, value);
    }

    /**
     * Set the <code>plugin</code> parameter IN value to the routine
     */
    public void setPlugin(String value) {
        setValue(PLUGIN, value);
    }

    /**
     * Set the <code>temporary</code> parameter IN value to the routine
     */
    public void setTemporary(Boolean value) {
        setValue(TEMPORARY, value);
    }

    /**
     * Set the <code>twophase</code> parameter IN value to the routine
     */
    public void setTwophase(Boolean value) {
        setValue(TWOPHASE, value);
    }

    /**
     * Set the <code>failover</code> parameter IN value to the routine
     */
    public void setFailover(Boolean value) {
        setValue(FAILOVER, value);
    }

    /**
     * Get the <code>slot_name</code> parameter OUT value from the routine
     */
    public String getSlotName1() {
        return get(SLOT_NAME1);
    }

    /**
     * Get the <code>slot_name</code> parameter OUT value from the routine
     */
    public String getSlotName6() {
        return get(SLOT_NAME6);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getLsn() {
        return get(LSN);
    }
}
