/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.routines;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgSplitWalfileName extends AbstractRoutine<java.lang.Void> {

    /**
     * The parameter <code>pg_catalog.pg_split_walfile_name.file_name</code>.
     */
    public static final Parameter<String> FILE_NAME = Internal.createParameter("file_name", SQLDataType.CLOB, false, false);
    /**
     * The parameter
     * <code>pg_catalog.pg_split_walfile_name.segment_number</code>.
     */
    public static final Parameter<BigDecimal> SEGMENT_NUMBER = Internal.createParameter("segment_number", SQLDataType.NUMERIC, false, false);
    /**
     * The parameter <code>pg_catalog.pg_split_walfile_name.timeline_id</code>.
     */
    public static final Parameter<Long> TIMELINE_ID = Internal.createParameter("timeline_id", SQLDataType.BIGINT, false, false);
    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public PgSplitWalfileName() {
        super("pg_split_walfile_name", PgCatalog.PG_CATALOG);

        addInParameter(FILE_NAME);
        addOutParameter(SEGMENT_NUMBER);
        addOutParameter(TIMELINE_ID);
    }

    /**
     * Set the <code>file_name</code> parameter IN value to the routine
     */
    public void setFileName(String value) {
        setValue(FILE_NAME, value);
    }

    /**
     * Get the <code>segment_number</code> parameter OUT value from the routine
     */
    public BigDecimal getSegmentNumber() {
        return get(SEGMENT_NUMBER);
    }

    /**
     * Get the <code>timeline_id</code> parameter OUT value from the routine
     */
    public Long getTimelineId() {
        return get(TIMELINE_ID);
    }
}
