/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.routines;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Random3 extends AbstractRoutine<Long> {

    /**
     * The parameter <code>pg_catalog.random.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);
    /**
     * The parameter <code>pg_catalog.random.min</code>.
     */
    public static final Parameter<Long> MIN = Internal.createParameter("min", SQLDataType.BIGINT, false, false);
    /**
     * The parameter <code>pg_catalog.random.max</code>.
     */
    public static final Parameter<Long> MAX = Internal.createParameter("max", SQLDataType.BIGINT, false, false);
    private static final long serialVersionUID = 1L;

    /**
     * Create a new routine call instance
     */
    public Random3() {
        super("random", PgCatalog.PG_CATALOG, SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(MIN);
        addInParameter(MAX);
        setOverloaded(true);
    }

    /**
     * Set the <code>min</code> parameter IN value to the routine
     */
    public void setMin(Long value) {
        setValue(MIN, value);
    }

    /**
     * Set the <code>min</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setMin(Field<Long> field) {
        setField(MIN, field);
    }

    /**
     * Set the <code>max</code> parameter IN value to the routine
     */
    public void setMax(Long value) {
        setValue(MAX, value);
    }

    /**
     * Set the <code>max</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setMax(Field<Long> field) {
        setField(MAX, field);
    }
}
