/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables;


import bookmanagementsystem.jooq.pg_catalog.Keys;
import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import bookmanagementsystem.jooq.pg_catalog.tables.records.PgAmprocRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgAmproc extends TableImpl<PgAmprocRecord> {

    /**
     * The reference instance of <code>pg_catalog.pg_amproc</code>
     */
    public static final PgAmproc PG_AMPROC = new PgAmproc();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>pg_catalog.pg_amproc.oid</code>.
     */
    public final TableField<PgAmprocRecord, Long> OID = createField(DSL.name("oid"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_amproc.amprocfamily</code>.
     */
    public final TableField<PgAmprocRecord, Long> AMPROCFAMILY = createField(DSL.name("amprocfamily"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_amproc.amproclefttype</code>.
     */
    public final TableField<PgAmprocRecord, Long> AMPROCLEFTTYPE = createField(DSL.name("amproclefttype"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_amproc.amprocrighttype</code>.
     */
    public final TableField<PgAmprocRecord, Long> AMPROCRIGHTTYPE = createField(DSL.name("amprocrighttype"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_amproc.amprocnum</code>.
     */
    public final TableField<PgAmprocRecord, Short> AMPROCNUM = createField(DSL.name("amprocnum"), SQLDataType.SMALLINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_amproc.amproc</code>.
     */
    public final TableField<PgAmprocRecord, String> AMPROC = createField(DSL.name("amproc"), SQLDataType.VARCHAR.nullable(false), this, "");

    private PgAmproc(Name alias, Table<PgAmprocRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PgAmproc(Name alias, Table<PgAmprocRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_amproc</code> table reference
     */
    public PgAmproc(String alias) {
        this(DSL.name(alias), PG_AMPROC);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_amproc</code> table reference
     */
    public PgAmproc(Name alias) {
        this(alias, PG_AMPROC);
    }

    /**
     * Create a <code>pg_catalog.pg_amproc</code> table reference
     */
    public PgAmproc() {
        this(DSL.name("pg_amproc"), null);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgAmprocRecord> getRecordType() {
        return PgAmprocRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public UniqueKey<PgAmprocRecord> getPrimaryKey() {
        return Keys.PG_AMPROC_OID_INDEX;
    }

    @Override
    public List<UniqueKey<PgAmprocRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PG_AMPROC_FAM_PROC_INDEX);
    }

    @Override
    public PgAmproc as(String alias) {
        return new PgAmproc(DSL.name(alias), this);
    }

    @Override
    public PgAmproc as(Name alias) {
        return new PgAmproc(alias, this);
    }

    @Override
    public PgAmproc as(Table<?> alias) {
        return new PgAmproc(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgAmproc rename(String name) {
        return new PgAmproc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgAmproc rename(Name name) {
        return new PgAmproc(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgAmproc rename(Table<?> name) {
        return new PgAmproc(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc where(Condition condition) {
        return new PgAmproc(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgAmproc where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgAmproc where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgAmproc where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgAmproc where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgAmproc whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
