/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import bookmanagementsystem.jooq.pg_catalog.tables.records.PgLsLogdirRecord;

import java.time.OffsetDateTime;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgLsLogdir extends TableImpl<PgLsLogdirRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pg_catalog.pg_ls_logdir</code>
     */
    public static final PgLsLogdir PG_LS_LOGDIR = new PgLsLogdir();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgLsLogdirRecord> getRecordType() {
        return PgLsLogdirRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_ls_logdir.name</code>.
     */
    public final TableField<PgLsLogdirRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_ls_logdir.size</code>.
     */
    public final TableField<PgLsLogdirRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>pg_catalog.pg_ls_logdir.modification</code>.
     */
    public final TableField<PgLsLogdirRecord, OffsetDateTime> MODIFICATION = createField(DSL.name("modification"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PgLsLogdir(Name alias, Table<PgLsLogdirRecord> aliased) {
        this(alias, aliased, new Field[] {
        });
    }

    private PgLsLogdir(Name alias, Table<PgLsLogdirRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private PgLsLogdir(Name alias, Table<PgLsLogdirRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_ls_logdir</code> table reference
     */
    public PgLsLogdir(String alias) {
        this(DSL.name(alias), PG_LS_LOGDIR);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_ls_logdir</code> table reference
     */
    public PgLsLogdir(Name alias) {
        this(alias, PG_LS_LOGDIR);
    }

    /**
     * Create a <code>pg_catalog.pg_ls_logdir</code> table reference
     */
    public PgLsLogdir() {
        this(DSL.name("pg_ls_logdir"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public PgLsLogdir as(String alias) {
        return new PgLsLogdir(DSL.name(alias), this, parameters);
    }

    @Override
    public PgLsLogdir as(Name alias) {
        return new PgLsLogdir(alias, this, parameters);
    }

    @Override
    public PgLsLogdir as(Table<?> alias) {
        return new PgLsLogdir(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsLogdir rename(String name) {
        return new PgLsLogdir(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsLogdir rename(Name name) {
        return new PgLsLogdir(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsLogdir rename(Table<?> name) {
        return new PgLsLogdir(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public PgLsLogdir call() {
        PgLsLogdir result = new PgLsLogdir(DSL.name("pg_ls_logdir"), null, new Field[] {});

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
