/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables;


import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import bookmanagementsystem.jooq.pg_catalog.tables.records.PgLsReplslotdirRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgLsReplslotdir extends TableImpl<PgLsReplslotdirRecord> {

    /**
     * The reference instance of <code>pg_catalog.pg_ls_replslotdir</code>
     */
    public static final PgLsReplslotdir PG_LS_REPLSLOTDIR = new PgLsReplslotdir();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>pg_catalog.pg_ls_replslotdir.name</code>.
     */
    public final TableField<PgLsReplslotdirRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");
    /**
     * The column <code>pg_catalog.pg_ls_replslotdir.size</code>.
     */
    public final TableField<PgLsReplslotdirRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT, this, "");
    /**
     * The column <code>pg_catalog.pg_ls_replslotdir.modification</code>.
     */
    public final TableField<PgLsReplslotdirRecord, OffsetDateTime> MODIFICATION = createField(DSL.name("modification"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PgLsReplslotdir(Name alias, Table<PgLsReplslotdirRecord> aliased) {
        this(alias, aliased, new Field[]{
                DSL.val(null, SQLDataType.CLOB)
        });
    }

    private PgLsReplslotdir(Name alias, Table<PgLsReplslotdirRecord> aliased, Field<?>[] parameters) {
        this(alias, aliased, parameters, null);
    }

    private PgLsReplslotdir(Name alias, Table<PgLsReplslotdirRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_ls_replslotdir</code> table
     * reference
     */
    public PgLsReplslotdir(String alias) {
        this(DSL.name(alias), PG_LS_REPLSLOTDIR);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_ls_replslotdir</code> table
     * reference
     */
    public PgLsReplslotdir(Name alias) {
        this(alias, PG_LS_REPLSLOTDIR);
    }

    /**
     * Create a <code>pg_catalog.pg_ls_replslotdir</code> table reference
     */
    public PgLsReplslotdir() {
        this(DSL.name("pg_ls_replslotdir"), null);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgLsReplslotdirRecord> getRecordType() {
        return PgLsReplslotdirRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public PgLsReplslotdir as(String alias) {
        return new PgLsReplslotdir(DSL.name(alias), this, parameters);
    }

    @Override
    public PgLsReplslotdir as(Name alias) {
        return new PgLsReplslotdir(alias, this, parameters);
    }

    @Override
    public PgLsReplslotdir as(Table<?> alias) {
        return new PgLsReplslotdir(alias.getQualifiedName(), this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsReplslotdir rename(String name) {
        return new PgLsReplslotdir(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsReplslotdir rename(Name name) {
        return new PgLsReplslotdir(name, null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public PgLsReplslotdir rename(Table<?> name) {
        return new PgLsReplslotdir(name.getQualifiedName(), null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public PgLsReplslotdir call(
            String slotName
    ) {
        PgLsReplslotdir result = new PgLsReplslotdir(DSL.name("pg_ls_replslotdir"), null, new Field[]{
                DSL.val(slotName, SQLDataType.CLOB)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public PgLsReplslotdir call(
            Field<String> slotName
    ) {
        PgLsReplslotdir result = new PgLsReplslotdir(DSL.name("pg_ls_replslotdir"), null, new Field[]{
                slotName
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
