/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables;


import bookmanagementsystem.jooq.pg_catalog.Keys;
import bookmanagementsystem.jooq.pg_catalog.PgCatalog;
import bookmanagementsystem.jooq.pg_catalog.tables.records.PgShdescriptionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgShdescription extends TableImpl<PgShdescriptionRecord> {

    /**
     * The reference instance of <code>pg_catalog.pg_shdescription</code>
     */
    public static final PgShdescription PG_SHDESCRIPTION = new PgShdescription();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>pg_catalog.pg_shdescription.objoid</code>.
     */
    public final TableField<PgShdescriptionRecord, Long> OBJOID = createField(DSL.name("objoid"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_shdescription.classoid</code>.
     */
    public final TableField<PgShdescriptionRecord, Long> CLASSOID = createField(DSL.name("classoid"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>pg_catalog.pg_shdescription.description</code>.
     */
    public final TableField<PgShdescriptionRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private PgShdescription(Name alias, Table<PgShdescriptionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PgShdescription(Name alias, Table<PgShdescriptionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_shdescription</code> table
     * reference
     */
    public PgShdescription(String alias) {
        this(DSL.name(alias), PG_SHDESCRIPTION);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_shdescription</code> table
     * reference
     */
    public PgShdescription(Name alias) {
        this(alias, PG_SHDESCRIPTION);
    }

    /**
     * Create a <code>pg_catalog.pg_shdescription</code> table reference
     */
    public PgShdescription() {
        this(DSL.name("pg_shdescription"), null);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgShdescriptionRecord> getRecordType() {
        return PgShdescriptionRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public UniqueKey<PgShdescriptionRecord> getPrimaryKey() {
        return Keys.PG_SHDESCRIPTION_O_C_INDEX;
    }

    @Override
    public PgShdescription as(String alias) {
        return new PgShdescription(DSL.name(alias), this);
    }

    @Override
    public PgShdescription as(Name alias) {
        return new PgShdescription(alias, this);
    }

    @Override
    public PgShdescription as(Table<?> alias) {
        return new PgShdescription(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgShdescription rename(String name) {
        return new PgShdescription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgShdescription rename(Name name) {
        return new PgShdescription(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgShdescription rename(Table<?> name) {
        return new PgShdescription(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription where(Condition condition) {
        return new PgShdescription(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgShdescription where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgShdescription where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgShdescription where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgShdescription where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgShdescription whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
