/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgAmop;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgAmopRecord extends UpdatableRecordImpl<PgAmopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgAmopRecord
     */
    public PgAmopRecord() {
        super(PgAmop.PG_AMOP);
    }

    /**
     * Create a detached, initialised PgAmopRecord
     */
    public PgAmopRecord(Long oid, Long amopfamily, Long amoplefttype, Long amoprighttype, Short amopstrategy, String amoppurpose, Long amopopr, Long amopmethod, Long amopsortfamily) {
        super(PgAmop.PG_AMOP);

        setOid(oid);
        setAmopfamily(amopfamily);
        setAmoplefttype(amoplefttype);
        setAmoprighttype(amoprighttype);
        setAmopstrategy(amopstrategy);
        setAmoppurpose(amoppurpose);
        setAmopopr(amopopr);
        setAmopmethod(amopmethod);
        setAmopsortfamily(amopsortfamily);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amopfamily</code>.
     */
    public Long getAmopfamily() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amopfamily</code>.
     */
    public void setAmopfamily(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amoplefttype</code>.
     */
    public Long getAmoplefttype() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amoplefttype</code>.
     */
    public void setAmoplefttype(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amoprighttype</code>.
     */
    public Long getAmoprighttype() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amoprighttype</code>.
     */
    public void setAmoprighttype(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amopstrategy</code>.
     */
    public Short getAmopstrategy() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amopstrategy</code>.
     */
    public void setAmopstrategy(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amoppurpose</code>.
     */
    public String getAmoppurpose() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amoppurpose</code>.
     */
    public void setAmoppurpose(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amopopr</code>.
     */
    public Long getAmopopr() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amopopr</code>.
     */
    public void setAmopopr(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_amop.amopmethod</code>.
     */
    public Long getAmopmethod() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_amop.amopmethod</code>.
     */
    public void setAmopmethod(Long value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_amop.amopsortfamily</code>.
     */
    public Long getAmopsortfamily() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pg_catalog.pg_amop.amopsortfamily</code>.
     */
    public void setAmopsortfamily(Long value) {
        set(8, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }
}
