/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgIndexes;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgIndexesRecord extends TableRecordImpl<PgIndexesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_indexes.schemaname</code>.
     */
    public void setSchemaname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_indexes.schemaname</code>.
     */
    public String getSchemaname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_indexes.tablename</code>.
     */
    public void setTablename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_indexes.tablename</code>.
     */
    public String getTablename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_indexes.indexname</code>.
     */
    public void setIndexname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_indexes.indexname</code>.
     */
    public String getIndexname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_indexes.tablespace</code>.
     */
    public void setTablespace(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_indexes.tablespace</code>.
     */
    public String getTablespace() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_indexes.indexdef</code>.
     */
    public void setIndexdef(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_indexes.indexdef</code>.
     */
    public String getIndexdef() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgIndexesRecord
     */
    public PgIndexesRecord() {
        super(PgIndexes.PG_INDEXES);
    }

    /**
     * Create a detached, initialised PgIndexesRecord
     */
    public PgIndexesRecord(String schemaname, String tablename, String indexname, String tablespace, String indexdef) {
        super(PgIndexes.PG_INDEXES);

        setSchemaname(schemaname);
        setTablename(tablename);
        setIndexname(indexname);
        setTablespace(tablespace);
        setIndexdef(indexdef);
        resetChangedOnNotNull();
    }
}
