/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgLsLogicalsnapdir;
import org.jooq.impl.TableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgLsLogicalsnapdirRecord extends TableRecordImpl<PgLsLogicalsnapdirRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgLsLogicalsnapdirRecord
     */
    public PgLsLogicalsnapdirRecord() {
        super(PgLsLogicalsnapdir.PG_LS_LOGICALSNAPDIR);
    }

    /**
     * Create a detached, initialised PgLsLogicalsnapdirRecord
     */
    public PgLsLogicalsnapdirRecord(String name, Long size, OffsetDateTime modification) {
        super(PgLsLogicalsnapdir.PG_LS_LOGICALSNAPDIR);

        setName(name);
        setSize(size);
        setModification(modification);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_ls_logicalsnapdir.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_ls_logicalsnapdir.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_ls_logicalsnapdir.size</code>.
     */
    public Long getSize() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_ls_logicalsnapdir.size</code>.
     */
    public void setSize(Long value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_ls_logicalsnapdir.modification</code>.
     */
    public OffsetDateTime getModification() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_ls_logicalsnapdir.modification</code>.
     */
    public void setModification(OffsetDateTime value) {
        set(2, value);
    }
}
