/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgOperator;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgOperatorRecord extends UpdatableRecordImpl<PgOperatorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgOperatorRecord
     */
    public PgOperatorRecord() {
        super(PgOperator.PG_OPERATOR);
    }

    /**
     * Create a detached, initialised PgOperatorRecord
     */
    public PgOperatorRecord(Long oid, String oprname, Long oprnamespace, Long oprowner, String oprkind, Boolean oprcanmerge, Boolean oprcanhash, Long oprleft, Long oprright, Long oprresult, Long oprcom, Long oprnegate, String oprcode, String oprrest, String oprjoin) {
        super(PgOperator.PG_OPERATOR);

        setOid(oid);
        setOprname(oprname);
        setOprnamespace(oprnamespace);
        setOprowner(oprowner);
        setOprkind(oprkind);
        setOprcanmerge(oprcanmerge);
        setOprcanhash(oprcanhash);
        setOprleft(oprleft);
        setOprright(oprright);
        setOprresult(oprresult);
        setOprcom(oprcom);
        setOprnegate(oprnegate);
        setOprcode(oprcode);
        setOprrest(oprrest);
        setOprjoin(oprjoin);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oid</code>.
     */
    public Long getOid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oid</code>.
     */
    public void setOid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprname</code>.
     */
    public String getOprname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprname</code>.
     */
    public void setOprname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprnamespace</code>.
     */
    public Long getOprnamespace() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprnamespace</code>.
     */
    public void setOprnamespace(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprowner</code>.
     */
    public Long getOprowner() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprowner</code>.
     */
    public void setOprowner(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprkind</code>.
     */
    public String getOprkind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprkind</code>.
     */
    public void setOprkind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprcanmerge</code>.
     */
    public Boolean getOprcanmerge() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprcanmerge</code>.
     */
    public void setOprcanmerge(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprcanhash</code>.
     */
    public Boolean getOprcanhash() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprcanhash</code>.
     */
    public void setOprcanhash(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprleft</code>.
     */
    public Long getOprleft() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprleft</code>.
     */
    public void setOprleft(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprright</code>.
     */
    public Long getOprright() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprright</code>.
     */
    public void setOprright(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprresult</code>.
     */
    public Long getOprresult() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprresult</code>.
     */
    public void setOprresult(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprcom</code>.
     */
    public Long getOprcom() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprcom</code>.
     */
    public void setOprcom(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprnegate</code>.
     */
    public Long getOprnegate() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprnegate</code>.
     */
    public void setOprnegate(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprcode</code>.
     */
    public String getOprcode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprcode</code>.
     */
    public void setOprcode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_operator.oprrest</code>.
     */
    public String getOprrest() {
        return (String) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_operator.oprrest</code>.
     */
    public void setOprrest(String value) {
        set(13, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_operator.oprjoin</code>.
     */
    public String getOprjoin() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pg_catalog.pg_operator.oprjoin</code>.
     */
    public void setOprjoin(String value) {
        set(14, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }
}
