/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgPartitionedTable;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgPartitionedTableRecord extends UpdatableRecordImpl<PgPartitionedTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgPartitionedTableRecord
     */
    public PgPartitionedTableRecord() {
        super(PgPartitionedTable.PG_PARTITIONED_TABLE);
    }

    /**
     * Create a detached, initialised PgPartitionedTableRecord
     */
    public PgPartitionedTableRecord(Long partrelid, String partstrat, Short partnatts, Long partdefid, Object[] partattrs, Object[] partclass, Object[] partcollation, Object partexprs) {
        super(PgPartitionedTable.PG_PARTITIONED_TABLE);

        setPartrelid(partrelid);
        setPartstrat(partstrat);
        setPartnatts(partnatts);
        setPartdefid(partdefid);
        setPartattrs(partattrs);
        setPartclass(partclass);
        setPartcollation(partcollation);
        setPartexprs(partexprs);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partrelid</code>.
     */
    public Long getPartrelid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partrelid</code>.
     */
    public void setPartrelid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partstrat</code>.
     */
    public String getPartstrat() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partstrat</code>.
     */
    public void setPartstrat(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partnatts</code>.
     */
    public Short getPartnatts() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partnatts</code>.
     */
    public void setPartnatts(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partdefid</code>.
     */
    public Long getPartdefid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partdefid</code>.
     */
    public void setPartdefid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partattrs</code>.
     */
    public Object[] getPartattrs() {
        return (Object[]) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partattrs</code>.
     */
    public void setPartattrs(Object[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partclass</code>.
     */
    public Object[] getPartclass() {
        return (Object[]) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partclass</code>.
     */
    public void setPartclass(Object[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_partitioned_table.partcollation</code>.
     */
    public Object[] getPartcollation() {
        return (Object[]) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_partitioned_table.partcollation</code>.
     */
    public void setPartcollation(Object[] value) {
        set(6, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getPartexprs() {
        return get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setPartexprs(Object value) {
        set(7, value);
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }
}
