/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgShdescription;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgShdescriptionRecord extends UpdatableRecordImpl<PgShdescriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgShdescriptionRecord
     */
    public PgShdescriptionRecord() {
        super(PgShdescription.PG_SHDESCRIPTION);
    }

    /**
     * Create a detached, initialised PgShdescriptionRecord
     */
    public PgShdescriptionRecord(Long objoid, Long classoid, String description) {
        super(PgShdescription.PG_SHDESCRIPTION);

        setObjoid(objoid);
        setClassoid(classoid);
        setDescription(description);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_shdescription.objoid</code>.
     */
    public Long getObjoid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_shdescription.objoid</code>.
     */
    public void setObjoid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_shdescription.classoid</code>.
     */
    public Long getClassoid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_shdescription.classoid</code>.
     */
    public void setClassoid(Long value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_shdescription.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pg_catalog.pg_shdescription.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }
}
