/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgStats;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgStatsRecord extends TableRecordImpl<PgStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgStatsRecord
     */
    public PgStatsRecord() {
        super(PgStats.PG_STATS);
    }

    /**
     * Create a detached, initialised PgStatsRecord
     */
    public PgStatsRecord(String schemaname, String tablename, String attname, Boolean inherited, Float nullFrac, Integer avgWidth, Float nDistinct, Object[] mostCommonVals, Float[] mostCommonFreqs, Object[] histogramBounds, Float correlation, Object[] mostCommonElems, Float[] mostCommonElemFreqs, Float[] elemCountHistogram, Object[] rangeLengthHistogram, Float rangeEmptyFrac, Object[] rangeBoundsHistogram) {
        super(PgStats.PG_STATS);

        setSchemaname(schemaname);
        setTablename(tablename);
        setAttname(attname);
        setInherited(inherited);
        setNullFrac(nullFrac);
        setAvgWidth(avgWidth);
        setNDistinct(nDistinct);
        setMostCommonVals(mostCommonVals);
        setMostCommonFreqs(mostCommonFreqs);
        setHistogramBounds(histogramBounds);
        setCorrelation(correlation);
        setMostCommonElems(mostCommonElems);
        setMostCommonElemFreqs(mostCommonElemFreqs);
        setElemCountHistogram(elemCountHistogram);
        setRangeLengthHistogram(rangeLengthHistogram);
        setRangeEmptyFrac(rangeEmptyFrac);
        setRangeBoundsHistogram(rangeBoundsHistogram);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.schemaname</code>.
     */
    public String getSchemaname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.schemaname</code>.
     */
    public void setSchemaname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.tablename</code>.
     */
    public String getTablename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.tablename</code>.
     */
    public void setTablename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.attname</code>.
     */
    public String getAttname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.attname</code>.
     */
    public void setAttname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.inherited</code>.
     */
    public Boolean getInherited() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.inherited</code>.
     */
    public void setInherited(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.null_frac</code>.
     */
    public Float getNullFrac() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.null_frac</code>.
     */
    public void setNullFrac(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.avg_width</code>.
     */
    public Integer getAvgWidth() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.avg_width</code>.
     */
    public void setAvgWidth(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.n_distinct</code>.
     */
    public Float getNDistinct() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.n_distinct</code>.
     */
    public void setNDistinct(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.most_common_vals</code>.
     */
    public Object[] getMostCommonVals() {
        return (Object[]) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.most_common_vals</code>.
     */
    public void setMostCommonVals(Object[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.most_common_freqs</code>.
     */
    public Float[] getMostCommonFreqs() {
        return (Float[]) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.most_common_freqs</code>.
     */
    public void setMostCommonFreqs(Float[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.histogram_bounds</code>.
     */
    public Object[] getHistogramBounds() {
        return (Object[]) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.histogram_bounds</code>.
     */
    public void setHistogramBounds(Object[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.correlation</code>.
     */
    public Float getCorrelation() {
        return (Float) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.correlation</code>.
     */
    public void setCorrelation(Float value) {
        set(10, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.most_common_elems</code>.
     */
    public Object[] getMostCommonElems() {
        return (Object[]) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.most_common_elems</code>.
     */
    public void setMostCommonElems(Object[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.most_common_elem_freqs</code>.
     */
    public Float[] getMostCommonElemFreqs() {
        return (Float[]) get(12);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.most_common_elem_freqs</code>.
     */
    public void setMostCommonElemFreqs(Float[] value) {
        set(12, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.elem_count_histogram</code>.
     */
    public Float[] getElemCountHistogram() {
        return (Float[]) get(13);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.elem_count_histogram</code>.
     */
    public void setElemCountHistogram(Float[] value) {
        set(13, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.range_length_histogram</code>.
     */
    public Object[] getRangeLengthHistogram() {
        return (Object[]) get(14);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.range_length_histogram</code>.
     */
    public void setRangeLengthHistogram(Object[] value) {
        set(14, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stats.range_empty_frac</code>.
     */
    public Float getRangeEmptyFrac() {
        return (Float) get(15);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.range_empty_frac</code>.
     */
    public void setRangeEmptyFrac(Float value) {
        set(15, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_stats.range_bounds_histogram</code>.
     */
    public Object[] getRangeBoundsHistogram() {
        return (Object[]) get(16);
    }

    /**
     * Setter for <code>pg_catalog.pg_stats.range_bounds_histogram</code>.
     */
    public void setRangeBoundsHistogram(Object[] value) {
        set(16, value);
    }
}
