/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgStatGetWalSenders;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.YearToSecond;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgStatGetWalSendersRecord extends TableRecordImpl<PgStatGetWalSendersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgStatGetWalSendersRecord
     */
    public PgStatGetWalSendersRecord() {
        super(PgStatGetWalSenders.PG_STAT_GET_WAL_SENDERS);
    }

    /**
     * Create a detached, initialised PgStatGetWalSendersRecord
     */
    public PgStatGetWalSendersRecord(Integer pid, String state, Object sentLsn, Object writeLsn, Object flushLsn, Object replayLsn, YearToSecond writeLag, YearToSecond flushLag, YearToSecond replayLag, Integer syncPriority, String syncState, OffsetDateTime replyTime) {
        super(PgStatGetWalSenders.PG_STAT_GET_WAL_SENDERS);

        setPid(pid);
        setState(state);
        setSentLsn(sentLsn);
        setWriteLsn(writeLsn);
        setFlushLsn(flushLsn);
        setReplayLsn(replayLsn);
        setWriteLag(writeLag);
        setFlushLag(flushLag);
        setReplayLag(replayLag);
        setSyncPriority(syncPriority);
        setSyncState(syncState);
        setReplyTime(replyTime);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.state</code>.
     */
    public String getState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.state</code>.
     */
    public void setState(String value) {
        set(1, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getSentLsn() {
        return get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setSentLsn(Object value) {
        set(2, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getWriteLsn() {
        return get(3);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setWriteLsn(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getFlushLsn() {
        return get(4);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setFlushLsn(Object value) {
        set(4, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getReplayLsn() {
        return get(5);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setReplayLsn(Object value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.write_lag</code>.
     */
    public YearToSecond getWriteLag() {
        return (YearToSecond) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.write_lag</code>.
     */
    public void setWriteLag(YearToSecond value) {
        set(6, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.flush_lag</code>.
     */
    public YearToSecond getFlushLag() {
        return (YearToSecond) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.flush_lag</code>.
     */
    public void setFlushLag(YearToSecond value) {
        set(7, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.replay_lag</code>.
     */
    public YearToSecond getReplayLag() {
        return (YearToSecond) get(8);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.replay_lag</code>.
     */
    public void setReplayLag(YearToSecond value) {
        set(8, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.sync_priority</code>.
     */
    public Integer getSyncPriority() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.sync_priority</code>.
     */
    public void setSyncPriority(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.sync_state</code>.
     */
    public String getSyncState() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.sync_state</code>.
     */
    public void setSyncState(String value) {
        set(10, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_stat_get_wal_senders.reply_time</code>.
     */
    public OffsetDateTime getReplyTime() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_get_wal_senders.reply_time</code>.
     */
    public void setReplyTime(OffsetDateTime value) {
        set(11, value);
    }
}
