/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgStatGssapi;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgStatGssapiRecord extends TableRecordImpl<PgStatGssapiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public void setPid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public void setGssAuthenticated(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.gss_authenticated</code>.
     */
    public Boolean getGssAuthenticated() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public void setPrincipal(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.principal</code>.
     */
    public String getPrincipal() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public void setEncrypted(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.encrypted</code>.
     */
    public Boolean getEncrypted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_gssapi.credentials_delegated</code>.
     */
    public void setCredentialsDelegated(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_gssapi.credentials_delegated</code>.
     */
    public Boolean getCredentialsDelegated() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatGssapiRecord
     */
    public PgStatGssapiRecord() {
        super(PgStatGssapi.PG_STAT_GSSAPI);
    }

    /**
     * Create a detached, initialised PgStatGssapiRecord
     */
    public PgStatGssapiRecord(Integer pid, Boolean gssAuthenticated, String principal, Boolean encrypted, Boolean credentialsDelegated) {
        super(PgStatGssapi.PG_STAT_GSSAPI);

        setPid(pid);
        setGssAuthenticated(gssAuthenticated);
        setPrincipal(principal);
        setEncrypted(encrypted);
        setCredentialsDelegated(credentialsDelegated);
        resetChangedOnNotNull();
    }
}
