/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgTables;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PgTablesRecord extends TableRecordImpl<PgTablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PgTablesRecord
     */
    public PgTablesRecord() {
        super(PgTables.PG_TABLES);
    }

    /**
     * Create a detached, initialised PgTablesRecord
     */
    public PgTablesRecord(String schemaname, String tablename, String tableowner, String tablespace, Boolean hasindexes, Boolean hasrules, Boolean hastriggers, Boolean rowsecurity) {
        super(PgTables.PG_TABLES);

        setSchemaname(schemaname);
        setTablename(tablename);
        setTableowner(tableowner);
        setTablespace(tablespace);
        setHasindexes(hasindexes);
        setHasrules(hasrules);
        setHastriggers(hastriggers);
        setRowsecurity(rowsecurity);
        resetChangedOnNotNull();
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.schemaname</code>.
     */
    public String getSchemaname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.schemaname</code>.
     */
    public void setSchemaname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.tablename</code>.
     */
    public String getTablename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.tablename</code>.
     */
    public void setTablename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.tableowner</code>.
     */
    public String getTableowner() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.tableowner</code>.
     */
    public void setTableowner(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.tablespace</code>.
     */
    public String getTablespace() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.tablespace</code>.
     */
    public void setTablespace(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.hasindexes</code>.
     */
    public Boolean getHasindexes() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.hasindexes</code>.
     */
    public void setHasindexes(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.hasrules</code>.
     */
    public Boolean getHasrules() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.hasrules</code>.
     */
    public void setHasrules(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_tables.hastriggers</code>.
     */
    public Boolean getHastriggers() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.hastriggers</code>.
     */
    public void setHastriggers(Boolean value) {
        set(6, value);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.pg_tables.rowsecurity</code>.
     */
    public Boolean getRowsecurity() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>pg_catalog.pg_tables.rowsecurity</code>.
     */
    public void setRowsecurity(Boolean value) {
        set(7, value);
    }
}
