/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.PgTimezoneAbbrevs;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgTimezoneAbbrevsRecord extends TableRecordImpl<PgTimezoneAbbrevsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.pg_timezone_abbrevs.abbrev</code>.
     */
    public void setAbbrev(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_timezone_abbrevs.abbrev</code>.
     */
    public String getAbbrev() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_timezone_abbrevs.utc_offset</code>.
     */
    public void setUtcOffset(YearToSecond value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_timezone_abbrevs.utc_offset</code>.
     */
    public YearToSecond getUtcOffset() {
        return (YearToSecond) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_timezone_abbrevs.is_dst</code>.
     */
    public void setIsDst(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_timezone_abbrevs.is_dst</code>.
     */
    public Boolean getIsDst() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgTimezoneAbbrevsRecord
     */
    public PgTimezoneAbbrevsRecord() {
        super(PgTimezoneAbbrevs.PG_TIMEZONE_ABBREVS);
    }

    /**
     * Create a detached, initialised PgTimezoneAbbrevsRecord
     */
    public PgTimezoneAbbrevsRecord(String abbrev, YearToSecond utcOffset, Boolean isDst) {
        super(PgTimezoneAbbrevs.PG_TIMEZONE_ABBREVS);

        setAbbrev(abbrev);
        setUtcOffset(utcOffset);
        setIsDst(isDst);
        resetChangedOnNotNull();
    }
}
