/*
 * This file is generated by jOOQ.
 */
package bookmanagementsystem.jooq.pg_catalog.tables.records;


import bookmanagementsystem.jooq.pg_catalog.tables.StringToTable;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StringToTableRecord extends TableRecordImpl<StringToTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached StringToTableRecord
     */
    public StringToTableRecord() {
        super(StringToTable.STRING_TO_TABLE);
    }

    /**
     * Create a detached, initialised StringToTableRecord
     */
    public StringToTableRecord(String stringToTable) {
        super(StringToTable.STRING_TO_TABLE);

        setStringToTable(stringToTable);
        resetChangedOnNotNull();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pg_catalog.string_to_table.string_to_table</code>.
     */
    public String getStringToTable() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.string_to_table.string_to_table</code>.
     */
    public void setStringToTable(String value) {
        set(0, value);
    }
}
